# Generated by Django 6.0.3 on 2026-03-17 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.CreateModel(
            name='EventFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], max_length=20)),
                ('total_fetched', models.IntegerField(default=0)),
                ('new_created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('prizes', models.JSONField(blank=True, default=list)),
                ('max_team_size', models.IntegerField(default=5)),
                ('min_team_size', models.IntegerField(default=1)),
                ('team_count', models.IntegerField(default=0)),
                ('participant_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status', '-start_date'], name='events_hack_status_7aa416_idx'), models.Index(fields=['difficulty', '-start_date'], name='events_hack_difficu_c5c847_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('current_registrations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcategory')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status', '-start_date'], name='events_even_status_489d0f_idx'), models.Index(fields=['is_featured', '-start_date'], name='events_even_is_feat_518e3f_idx')],
            },
        ),
    ]
