import React, { useState } from 'react';

// Icons needed for Calendar
const PlusIcon = ({ className }) => ( <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg> );
const ChevronLeftIcon = ({ className }) => ( <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="15 18 9 12 15 6"></polyline></svg> );
const ChevronRightIcon = ({ className }) => ( <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg> );
const XIcon = ({ className }) => ( <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg> );


const EventModal = ({ selectedDate, newEvent, setNewEvent, handleSaveEvent, setIsEventModalOpen }) => (
    // ... (Event Modal JSX remains the same) ...
    <div className="fixed inset-0 bg-black bg-opacity-60 flex items-center justify-center p-4 z-50 animate-fade-in"><div className="bg-white rounded-lg shadow-xl p-6 w-full max-w-md"><div className="flex justify-between items-center mb-4 border-b pb-3"><h3 className="text-xl font-bold text-gray-800">Add Event for {selectedDate.toLocaleDateString()}</h3><button onClick={() => setIsEventModalOpen(false)} className="text-gray-400 hover:text-gray-600"><XIcon className="w-6 h-6" /></button></div><form onSubmit={handleSaveEvent}><div className="space-y-4"><div><label className="block text-sm font-medium text-gray-700">Title</label><input type="text" value={newEvent.title} onChange={e => setNewEvent({...newEvent, title: e.target.value})} required className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm p-2 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"/></div><div><label className="block text-sm font-medium text-gray-700">Time</label><input type="time" value={newEvent.time} onChange={e => setNewEvent({...newEvent, time: e.target.value})} required className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm p-2 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"/></div><div><label className="block text-sm font-medium text-gray-700">Details (Optional)</label><textarea value={newEvent.details} onChange={e => setNewEvent({...newEvent, details: e.target.value})} rows="3" className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm p-2 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"></textarea></div><div><label className="block text-sm font-medium text-gray-700">Type</label><select value={newEvent.type} onChange={e => setNewEvent({...newEvent, type: e.target.value})} className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm p-2 bg-white focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"><option value="event">General Event</option><option value="important">Important Deadline</option><option value="hackathon">Hackathon/Competition</option></select></div></div><div className="mt-6 flex justify-end space-x-3"><button type="button" onClick={() => setIsEventModalOpen(false)} className="bg-gray-200 text-gray-700 font-medium py-2 px-4 rounded-lg hover:bg-gray-300 transition-colors">Cancel</button><button type="submit" className="bg-indigo-600 text-white font-medium py-2 px-4 rounded-lg hover:bg-indigo-700 transition-colors">Save Event</button></div></form></div></div>
);

const CalendarPage = ({ handleGenerateDaySummary, isGeneratingSummary }) => {
    console.log("Rendering: CalendarPage Component"); // Add log
    const [currentDate, setCurrentDate] = useState(new Date());
    const [selectedDate, setSelectedDate] = useState(new Date());
    const [isEventModalOpen, setIsEventModalOpen] = useState(false);
    const [newEvent, setNewEvent] = useState({ title: '', time: '10:00', type: 'event', details: '' });
    const [events, setEvents] = useState(() => { /* Mock data */ return []; }); // Keep mock data simple for now
    const daysOfWeek = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    const firstDay = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1).getDay();
    const daysInMonth = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0).getDate();
    const handlePrev = () => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
    const handleNext = () => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));
    const handleDateClick = (day) => { setSelectedDate(new Date(currentDate.getFullYear(), currentDate.getMonth(), day)); };
    const handleSave = (e) => { e.preventDefault(); setEvents([...events, {...newEvent, date: selectedDate.toISOString().split('T')[0]}]); setIsEventModalOpen(false); setNewEvent({ title: '', time: '10:00', type: 'event', details: '' }); };
    const selectedEvents = events.filter(ev => new Date(ev.date + 'T00:00:00').toDateString() === selectedDate.toDateString());
    const eventStyles = { important: { border: 'border-purple-500', bg: 'bg-purple-50', dot: 'bg-purple-500', text: 'text-purple-800', accent: 'text-purple-600' }, hackathon: { border: 'border-green-500', bg: 'bg-green-50', dot: 'bg-green-500', text: 'text-green-800', accent: 'text-green-600' }, event: { border: 'border-blue-500', bg: 'bg-blue-50', dot: 'bg-blue-500', text: 'text-blue-800', accent: 'text-blue-600' }};

    return ( /* Calendar JSX - simplified */
         <div className="flex flex-col lg:flex-row gap-6 md:gap-8">
            {isEventModalOpen && <EventModal selectedDate={selectedDate} newEvent={newEvent} setNewEvent={setNewEvent} handleSaveEvent={handleSave} setIsEventModalOpen={setIsEventModalOpen} />}
            {/* Calendar Grid */}
            <div className="flex-1 bg-white p-4 sm:p-6 rounded-xl shadow-lg border border-gray-200">
                <div className="flex justify-between items-center mb-4"> <button onClick={handlePrev} className="p-2 rounded-full hover:bg-gray-100 text-gray-500 hover:text-gray-700"><ChevronLeftIcon className="w-5 h-5" /></button> <h2 className="text-xl font-bold text-gray-800">{currentDate.toLocaleString('default', { month: 'long', year: 'numeric' })}</h2> <button onClick={handleNext} className="p-2 rounded-full hover:bg-gray-100 text-gray-500 hover:text-gray-700"><ChevronRightIcon className="w-5 h-5" /></button> </div>
                <div className="grid grid-cols-7 text-center text-xs font-semibold text-gray-500 mb-2"> {daysOfWeek.map(day => <div key={day} className="py-2">{day}</div>)} </div>
                <div className="grid grid-cols-7 border-t border-l border-gray-200"> {Array(firstDay).fill(null).map((_, i) => <div key={`e-${i}`} className="border-r border-b border-gray-200 h-20 sm:h-24 bg-gray-50"></div>)} {Array(daysInMonth).fill(null).map((_, i) => { const day=i+1; const dDate=new Date(currentDate.getFullYear(), currentDate.getMonth(), day); const isToday=dDate.toDateString()===new Date().toDateString(); const isSelected=selectedDate.toDateString()===dDate.toDateString(); const dEvents=events.filter(e=>new Date(e.date+'T00:00:00').toDateString()===dDate.toDateString()); return (<div key={day} onClick={()=>handleDateClick(day)} className={`border-r border-b border-gray-200 p-1.5 h-20 sm:h-24 cursor-pointer relative group ${isSelected?'bg-indigo-50':'hover:bg-gray-50'}`}><span className={`flex items-center justify-center w-7 h-7 rounded-full text-sm ${isToday?'bg-indigo-600 text-white font-bold':isSelected?'bg-indigo-200 text-indigo-800 font-semibold':'text-gray-700'}`}>{day}</span><div className="flex justify-start space-x-1 mt-1 pl-1 absolute bottom-1.5 left-1.5">{dEvents.slice(0,3).map((e,idx)=><div key={idx} className={`w-1.5 h-1.5 rounded-full ${eventStyles[e.type]?.dot??'bg-gray-400'}`}></div>)}{dEvents.length>3&&<span className="text-xs text-gray-400">+</span>}</div></div>)})} {Array((7-(firstDay+daysInMonth)%7)%7).fill(null).map((_,i)=><div key={`ee-${i}`} className="border-r border-b brd-gray-200 h-20 sm:h-24 bg-gray-50"></div>)} </div>
            </div>
            {/* Events List */}
            <div className="w-full lg:w-96 bg-white p-4 sm:p-6 rounded-xl shadow-lg border border-gray-200 flex flex-col">
                <div className="flex justify-between items-center mb-4 flex-shrink-0"><h3 className="text-lg font-bold text-gray-800">Schedule for {selectedDate.toLocaleDateString('default',{month:'short',day:'numeric'})}</h3><button onClick={()=>setIsEventModalOpen(true)} className="bg-indigo-100 text-indigo-600 rounded-full p-2 hover:bg-indigo-200 T focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-indigo-500"><PlusIcon className="w-5 h-5"/></button></div>
                <div className="space-y-3 flex-1 overflow-y-auto pr-2 custom-scrollbar">{selectedEvents.length>0?selectedEvents.sort((a,b)=>a.time.localeCompare(b.time)).map((ev,idx)=>(<div key={idx} className={`p-3 rounded-lg border-l-4 ${eventStyles[ev.type]?.border??'brd-gray-400'} ${eventStyles[ev.type]?.bg??'bg-gray-50'}`}><p className={`text-xs font-semibold ${eventStyles[ev.type]?.accent??'t-gray-500'}`}>{new Date(`1970-01-01T${ev.time}`).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</p><p className={`font-semibold mt-0.5 ${eventStyles[ev.type]?.text??'t-gray-800'}`}>{ev.title}</p>{ev.details&&<p className="text-sm t-gray-600 mt-1">{ev.details}</p>}</div>)):<p className="text-gray-500 text-center pt-10">No events scheduled.</p>}</div>
                {selectedEvents.length>0&&(<div className="mt-4 flex-shrink-0"><button onClick={()=>handleGenerateDaySummary(selectedEvents,selectedDate)} disabled={isGeneratingSummary} className="w-full text-center bg-indigo-50 hover:bg-indigo-100 text-indigo-700 font-semibold p-2.5 rounded-lg T flex items-center justify-center text-sm D">{isGeneratingSummary?'Summarizing...':'✨ Summarize Day'}</button></div>)}
            </div>
        </div>
    );
};

// --- ADD THIS LINE AT THE VERY BOTTOM ---
export default CalendarPage;