# Generated by Django 4.2.24 on 2026-03-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='requires_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
