# Generated by Django 4.2.24 on 2026-03-18 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available_on_campus', models.BooleanField(default=True)),
                ('on_campus_start_time', models.TimeField(blank=True, help_text='Daily start time for on-campus availability', null=True)),
                ('on_campus_end_time', models.TimeField(blank=True, help_text='Daily end time for on-campus availability', null=True)),
                ('on_campus_location', models.CharField(blank=True, help_text='Office location or room number', max_length=200, null=True)),
                ('on_campus_notes', models.TextField(blank=True, help_text='Additional notes for on-campus availability')),
                ('is_on_leave', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.OneToOneField(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty Availability',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('medical', 'Medical Leave'), ('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('maternity', 'Maternity Leave'), ('sabbatical', 'Sabbatical'), ('conference', 'Conference Leave'), ('other', 'Other Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('approval_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['faculty', '-start_date'], name='availabilit_faculty_150e07_idx'), models.Index(fields=['status', '-requested_at'], name='availabilit_status_68aac5_idx')],
            },
        ),
    ]
