# Generated by Django 4.2.24 on 2025-10-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_audience', models.CharField(choices=[('all', 'All'), ('student', 'Students Only'), ('faculty', 'Faculty Only')], default='all', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
