# Generated by Django 4.2.24 on 2026-03-18 02:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.OneToOneField(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_code', models.CharField(blank=True, max_length=50)),
                ('course_name', models.CharField(max_length=200)),
                ('lecture_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('lab', 'Lab'), ('tutorial', 'Tutorial'), ('seminar', 'Seminar'), ('invigilation', 'Invigilation'), ('mentorship', 'Mentorship'), ('office_hours', 'Office Hours'), ('other', 'Other')], default='theory', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, help_text='e.g., 2023-B1', max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='timetable.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('timetable', 'day_of_week', 'start_time', 'end_time', 'course_code')},
            },
        ),
    ]
