# Generated by Django 4.2.24 on 2026-03-18 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('target_audience', models.CharField(choices=[('all_students', 'All Students'), ('department', 'Department'), ('batch', 'Batch'), ('course', 'Course'), ('specific', 'Specific Students')], default='all_students', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_graded', models.BooleanField(default=False)),
                ('max_marks', models.FloatField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late')], default='assigned', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.studenttask')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='task_submissions/')),
                ('submission_link', models.URLField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_late', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='tasks.taskassignment')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['assignment', '-submitted_at'], name='tasks_tasks_assignm_b07f31_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['student', '-assigned_at'], name='tasks_taska_student_dd99db_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['status', '-assigned_at'], name='tasks_taska_status_15a0cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'student')},
        ),
        migrations.AddIndex(
            model_name='studenttask',
            index=models.Index(fields=['created_by', '-due_date'], name='tasks_stude_created_756891_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttask',
            index=models.Index(fields=['target_audience', '-due_date'], name='tasks_stude_target__3258f9_idx'),
        ),
    ]
