# Generated by Django 4.2.24 on 2026-03-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Session start time', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='title',
            field=models.CharField(blank=True, help_text='Session title (e.g., Lecture 1, Lab Session 1)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('IT', 'Information Technology'), ('BT', 'Biotechnology')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, help_text='Course end date for calendar selection', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='Course start date for calendar selection', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('course', 'date', 'start_time')},
        ),
        migrations.DeleteModel(
            name='SessionImage',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='time',
        ),
    ]
